#Copyright (C) 2025 Intel Corporation
#SPDX-License-Identifier: Apache-2.0
#+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
# +File name: ContMapSrv.srv
# +Description: Service definition for continuous mapping with specified parameters.
# +Author: Javier Felix-Rendon
# +Mail: javier.felix.rendon@intel.com
# +Version: 1.0
# +Date: 5/2/2025
#+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=

float32 start
float32 vertical
float32 horizontal
---
int64 sent