#/**
#Copyright (C) 2025 Intel Corporation
#SPDX-License-Identifier: Apache-2.0
#+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
# +File name: ControlPidStart.srv
# +Description: Service definition for starting PID control.
# +Author: Javier Felix-Rendon
# +Mail: javier.felix.rendon@intel.com
# +Version: 1.0
# +Date: 5/2/2025
#+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
#*/
int64 fase
---
int64 finish