/**
Copyright (C) 2025 Intel Corporation
SPDX-License-Identifier: Apache-2.0
+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
 +File name: WorldScan.srv
 +Description: Service definition for scanning the world grid with specified dimensions and steps.
 +Author: Javier Felix-Rendon
 +Mail: javier.felix.rendon@intel.com
 +Version: 1.0
 +Date: 5/2/2025
+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
*/
float32 x_grid_size
float32 y_grid_size
uint8 pan_steps
uint8 tilt_steps
float32 x_dimension
float32 y_dimension
---
uint8 finish