#/**
#Copyright (C) 2025 Intel Corporation
#SPDX-License-Identifier: Apache-2.0
#+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
# +File name: PosLidar.msg
# +Description: Message definition for position (pan, tilt, and lidar) in radians.
# +Author: Javier Felix-Rendon
# +Mail: javier.felix.rendon@intel.com
# +Version: 1.0
# +Date: 5/2/2025
#+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
#*/
#Position Pan and Tilt in radians
#Position lidar in radians

float32 pos_pan
float32 pos_tilt
float32 pos_lidar