/**
Copyright (C) 2025 Intel Corporation
SPDX-License-Identifier: Apache-2.0
+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
 +File name: PosVel.msg
 +Description: Message definition for position (pan and tilt) in radians and velocity of lidar in Hz.
 +Author: Javier Felix-Rendon
 +Mail: javier.felix.rendon@intel.com
 +Version: 1.0
 +Date: 5/2/2025
+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
*/
#Position Pan and Tilt in radians
#Velocity lidar in HZ

float32 pos_pan
float32 pos_tilt
float32 vel_lidar